{
 "title": "Conta Justa - Gustavo",
 "tags": [ "conta_justa" ],
 "time": { "from": "2020-04-05T16:42:39.263Z", "to": "2020-04-05T17:17:39.099Z" },
 "templating": {
  "list": [
   {
    "name": "userId",
    "query": "select id from server_user where name = 'Gustavo Ziyu Wang'"
   }
  ]
 },
 "panels": [
  {
   "title": "Painel do inquilino",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT name from server_user\nWHERE server_user.id = $userId"
    }
   ]
  },
  {
   "title": "Última medição",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT MAX(server_userbill.updated_at)\r\n\tFROM server_userbill\r\n\tWHERE server_userbill.user_id = $userId"
    }
   ]
  },
  {
   "title": "Preço a pagar - mês atual",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT MAX(server_userbill.amount) FROM server_userbill WHERE server_userbill.user_id = $userId"
    }
   ]
  },
  {
   "title": "Consumo anual (kWh) - Tendência",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT SUM(server_measurement.consumption) as month, date_trunc('month', server_measurement.measured_at) as time\r\n\tFROM server_measurement INNER JOIN server_equipment ON server_measurement.equipment_id = server_equipment.id\r\n\tWHERE server_measurement.measured_at >= date_trunc('year', CURRENT_DATE) and server_equipment.user_id = $userId\r\n\tGROUP by time"
    }
   ]
  },
  {
   "title": "Janeiro",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 3 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select ub.consumption \r\nfrom server_userbill ub \r\nleft join server_bill b on ub.bill_id = b.id\r\nwhere ub.user_id = $userId and b.month = 1\r\n"
    }
   ]
  },
  {
   "title": "Fevereiro",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 3 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select ub.consumption \r\nfrom server_userbill ub \r\nleft join server_bill b on ub.bill_id = b.id\r\nwhere ub.user_id = $userId and b.month = 2\r\n"
    }
   ]
  },
  {
   "title": "Março",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 3 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select ub.consumption \r\nfrom server_userbill ub \r\nleft join server_bill b on ub.bill_id = b.id\r\nwhere ub.user_id = $userId and b.month = 3"
    }
   ]
  },
  {
   "title": "Abril",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 3 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "select ub.consumption \r\nfrom server_userbill ub \r\nleft join server_bill b on ub.bill_id = b.id\r\nwhere ub.user_id = $userId and b.month = 4\r\n"
    }
   ]
  },
  {
   "title": "Maio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 6 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select ub.consumption \r\nfrom server_userbill ub \r\nleft join server_bill b on ub.bill_id = b.id\r\nwhere ub.user_id = $userId and b.month = 5\r\n"
    }
   ]
  },
  {
   "title": "Junho",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 6 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select ub.consumption \r\nfrom server_userbill ub \r\nleft join server_bill b on ub.bill_id = b.id\r\nwhere ub.user_id = $userId and b.month = 6\r\n"
    }
   ]
  },
  {
   "title": "Julho",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 6 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select ub.consumption \r\nfrom server_userbill ub \r\nleft join server_bill b on ub.bill_id = b.id\r\nwhere ub.user_id = $userId and b.month = 7\r\n"
    }
   ]
  },
  {
   "title": "Agosto",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 6 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select ub.consumption \r\nfrom server_userbill ub \r\nleft join server_bill b on ub.bill_id = b.id\r\nwhere ub.user_id = $userId and b.month = 8\r\n"
    }
   ]
  },
  {
   "title": "Setembro",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 9 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select ub.consumption \r\nfrom server_userbill ub \r\nleft join server_bill b on ub.bill_id = b.id\r\nwhere ub.user_id = $userId and b.month = 9"
    }
   ]
  },
  {
   "title": "Outubro",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 9 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select ub.consumption \r\nfrom server_userbill ub \r\nleft join server_bill b on ub.bill_id = b.id\r\nwhere ub.user_id = $userId and b.month = 10\r\n"
    }
   ]
  },
  {
   "title": "Novembro",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 9 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select ub.consumption \r\nfrom server_userbill ub \r\nleft join server_bill b on ub.bill_id = b.id\r\nwhere ub.user_id = $userId and b.month = 11\r\n"
    }
   ]
  },
  {
   "title": "Dezembro",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 9 },
   "format": "watth",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select ub.consumption \r\nfrom server_userbill ub \r\nleft join server_bill b on ub.bill_id = b.id\r\nwhere ub.user_id = $userId and b.month = 12\r\n"
    }
   ]
  },
  {
   "title": "Mês atual",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select ub.consumption\nfrom server_userbill ub\nleft join server_bill b on ub.bill_id = b.id\nwhere b.month = extract(month from CURRENT_DATE) and ub.user_id = $userId"
    }
   ]
  },
  {
   "title": "Número de inquilinos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 12 },
   "targets": [
    {
     "rawSql": "select count(*) from server_user where id <> 1;"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT SUM(server_measurement.consumption)\r\n\tFROM server_measurement INNER JOIN server_equipment ON server_measurement.equipment_id = server_equipment.id\r\n\tWHERE server_measurement.measured_at >= date_trunc('month', CURRENT_DATE)\r\n\tAND server_measurement.measured_at <= (date_trunc('month', CURRENT_DATE) + interval '1 month')\r\n\tAND server_equipment.user_id = 1"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "select SUM(ub.consumption)/COUNT(ub)\nfrom server_userbill ub\nleft join server_bill b on ub.bill_id = b.id\nwhere b.month = extract(month from CURRENT_DATE)"
    }
   ]
  }
 ]
}