# Generated by Django 3.0.4 on 2020-04-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_equipment_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='consumption',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
