# Generated by Django 3.0.4 on 2020-04-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20200405_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
