# Generated by Django 3.0.4 on 2020-04-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_auto_20200405_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='equipmentId',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='userequipment',
            old_name='equipmentId',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='userequipment',
            old_name='userId',
            new_name='user',
        ),
    ]
