# Generated by Django 3.0.4 on 2020-04-07 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20200405_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('consumption', models.DecimalField(decimal_places=3, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updatedAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='shared',
        ),
        migrations.AddField(
            model_name='equipment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='server.User'),
        ),
        migrations.DeleteModel(
            name='UserEquipment',
        ),
    ]
