# Generated by Django 3.0.4 on 2020-04-08 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_userbill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='measuredAt',
            new_name='measured_at',
        ),
        migrations.RenameField(
            model_name='userbill',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
