# Generated by Django 3.0.4 on 2020-04-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20200408_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
